# Generated by Django 4.2.2 on 2023-07-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_dislikes_remove_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
