# Generated by Django 4.2.2 on 2023-07-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_reaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
