# Generated by Django 4.2.2 on 2023-07-03 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=320, unique=True)),
                ('photo', models.ImageField(default='user_photos/user_default.png', upload_to='user_photos/<django.db.models.fields.CharField>')),
                ('join_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('birthday', models.DateField(null=True)),
                ('verified_badge', models.BooleanField(blank=True, default=False, null=True)),
                ('gender', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_superuser', models.BooleanField(blank=True, default=False, null=True)),
                ('is_admin', models.BooleanField(blank=True, default=False, null=True)),
                ('is_staff', models.BooleanField(blank=True, default=False, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
