# Generated by Django 4.2.2 on 2023-07-03 22:07

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='user_photos/user_default.png', upload_to=users.models.get_image_upload_path),
        ),
    ]
