# Generated by Django 4.2.2 on 2023-07-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_privite',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
